#!/usr/bin/env bash

if [ $# -lt 1 ] || [ "${#1}" -lt 4 ]; then
  echo "Enter at least 4 letters" "$1"
  exit
fi

CACHE_KEY=$1
CACHE_FILE="jisho-cache/$CACHE_KEY.json"

if [ ! -f $CACHE_FILE ]; then
  http GET https://jisho.org/api/v1/search/words?keyword=$CACHE_KEY > $CACHE_FILE
fi

cat $CACHE_FILE | jq --raw-output '.data | map(select(.japanese[0].word)) | map("\(.japanese[0].word)\t\(.japanese[0].reading)\t\(.senses[0].parts_of_speech[0])\t\(.senses[0].english_definitions[0])")[]' | sed "s/\([^	]\{30\}\)[^	]*/\1/g" | column -s$'\t' -t
